### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by scoobaspeaz** [bbriatte/homebridge-ps4-waker-platform#10]
Just wondering if the development for this has ended? I haven't seen any replies from the dev to issues. I too have some issues that others have had. This is a really awesome idea and was hoping the dev is still interested in this project.

**Comment by DenFav** [comment]
I hope he will get back at least to fix some of the issues, e.g. the plugin doesn't work at all:)

It is possible to power on/off a PS, and run the game. Cannot even imagine what else may be needed)

**Comment by OwlBawl** [comment]
Use Cmdswitch2 insted, works well

**Comment by bbriatte** [comment]
project updated
